STORES = [
    {
        "id": "farm",
        "name": "Farm Products",
        "tagline": "Fresh harvests and pantry staples",
        "summary": "Fresh produce, grains, honey, and dairy from trusted local suppliers.",
        "theme": "farm",
    },
    {
        "id": "wholesale",
        "name": "Wholesale Store",
        "tagline": "Bulk pricing for shops and buyers",
        "summary": "Bulk goods for retailers, restaurants, and families buying in volume.",
        "theme": "wholesale",
    },
    {
        "id": "perfumes",
        "name": "Perfume Store",
        "tagline": "Fragrances for daily wear and gifting",
        "summary": "Elegant scents with clean packaging, gift-ready sets, and everyday favorites.",
        "theme": "perfume",
    },
]

PRODUCTS = [
    {
        "id": "tomato-harvest-box",
        "storeId": "farm",
        "name": "Tomato Harvest Box",
        "detail": "Fresh red tomatoes packed for home kitchens and restaurants.",
        "price": 18,
        "unit": "per crate",
        "image": "assets/farm-tomatoes.svg",
    },
    {
        "id": "organic-honey-jar",
        "storeId": "farm",
        "name": "Organic Honey Jar",
        "detail": "Raw honey from local farms, sealed in glass jars.",
        "price": 12,
        "unit": "500 g",
        "image": "assets/farm-honey.svg",
    },
    {
        "id": "mixed-vegetable-basket",
        "storeId": "farm",
        "name": "Mixed Vegetable Basket",
        "detail": "Seasonal greens, carrots, peppers, and onions.",
        "price": 24,
        "unit": "basket",
        "image": "assets/farm-basket.svg",
    },
    {
        "id": "brown-eggs-tray",
        "storeId": "farm",
        "name": "Brown Eggs Tray",
        "detail": "Thirty farm eggs prepared for weekly household supply.",
        "price": 10,
        "unit": "30 pieces",
        "image": "assets/farm-eggs.svg",
    },
    {
        "id": "rice-bulk-sack",
        "storeId": "wholesale",
        "name": "Rice Bulk Sack",
        "detail": "Long-grain rice for shops, events, and family stores.",
        "price": 44,
        "unit": "25 kg",
        "image": "assets/wholesale-rice.svg",
    },
    {
        "id": "cooking-oil-carton",
        "storeId": "wholesale",
        "name": "Cooking Oil Carton",
        "detail": "Wholesale carton pricing for food businesses.",
        "price": 68,
        "unit": "12 bottles",
        "image": "assets/wholesale-oil.svg",
    },
    {
        "id": "maize-flour-bundle",
        "storeId": "wholesale",
        "name": "Maize Flour Bundle",
        "detail": "Fast-moving staple packed for retail shelves.",
        "price": 36,
        "unit": "10 packs",
        "image": "assets/wholesale-flour.svg",
    },
    {
        "id": "sugar-bale",
        "storeId": "wholesale",
        "name": "Sugar Bale",
        "detail": "Bulk sugar supply with dependable wholesale margins.",
        "price": 52,
        "unit": "20 kg",
        "image": "assets/wholesale-sugar.svg",
    },
    {
        "id": "amber-bloom",
        "storeId": "perfumes",
        "name": "Amber Bloom",
        "detail": "Warm amber, soft vanilla, and a polished evening finish.",
        "price": 39,
        "unit": "50 ml",
        "image": "assets/perfume-amber.svg",
    },
    {
        "id": "citrus-veil",
        "storeId": "perfumes",
        "name": "Citrus Veil",
        "detail": "Fresh citrus scent for bright daytime wear.",
        "price": 32,
        "unit": "50 ml",
        "image": "assets/perfume-citrus.svg",
    },
    {
        "id": "rose-noir-gift-set",
        "storeId": "perfumes",
        "name": "Rose Noir Gift Set",
        "detail": "Floral fragrance set with a deep rose signature.",
        "price": 58,
        "unit": "set",
        "image": "assets/perfume-rose.svg",
    },
    {
        "id": "ocean-musk",
        "storeId": "perfumes",
        "name": "Ocean Musk",
        "detail": "Clean aquatic musk with crisp daily freshness.",
        "price": 35,
        "unit": "50 ml",
        "image": "assets/perfume-ocean.svg",
    },
]
